CC=gcc
EX01=ex01
EX02=ex02
EX03=ex03
EX04=ex04
EX05=ex05
AL_LINK=-lawe
ifeq "$(ALFONT)" "1"
AL_LINK+=-lalfont
endif
ifeq "$(LOADPNG)" "1"
AL_LINK+=-lldpng -lpng -lz
endif
AL_LINK+=`allegro-config --libs`
ALL=$(EX01) $(EX02) $(EX03) $(EX04) $(EX05)